services:
  mysql_db:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "$MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT"



  app:
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    container_name: springboot-container
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - 5005:5005
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql_db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE"
        }'
    volumes:
      - .m2:/root/.m2
      - .:/app
    command: sh run.sh
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  mysql_data:
